jwt:
  secret: 5A7134743777217A24432646294A404E635266556A586E3272357538782F413F
server:
  port: 8008
  error:
    include-message: always
spring:
  profiles:
    include: oauth
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 150MB
      max-request-size: 180MB


mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*-mapping.xml

cloud:
  aws:
    s3:
      bucket: team3.finalproject
      url: https://s3.ap-northeast-3.amazonaws.com/team3.finalproject
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ap-northeast-3
      auto: false
    stack:
      auto: false

  logging:
    level:
      com:
        amazonaws:
          util:
            EC2MetadataUtils: ERROR
